steps:
#  - name: gcr.io/cloud-builders/git
#    id: Clone CD
#    secretEnv: [ 'TOKEN_GITHUB' ]
#    entrypoint: /bin/sh
#    args:
#      - '-c'
#      - |
#        cd /workspace && \
#        git clone https://AxlRoe:$$TOKEN_GITHUB@github.com/AxlRoe/$_CD_REPO.git

  - name: gcr.io/cloud-builders/mvn
    id: build
    args:
      - ["package", "-Pnative"]
    volumes:
      - name: m2
        path: /root/.m2/

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        gcloud functions deploy quarkus-example-http \
          --gen2 \
          --memory="256Mi"  \
          --max-instances=2 \
          --region $_REGION \
          --vpc-connector $_VPC_CONNECTOR \
          --entry-point=io.quarkus.gcp.functions.QuarkusHttpFunction \
          --runtime=java11 --trigger-http --allow-unauthenticated --source=/workspace/$REPO_NAME/functions/
    volumes:
      - name: 'm2'
        path: /root/.m2

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/$_SECRET_NAME/versions/latest
      env: 'TOKEN_GITHUB'
