steps:
  - name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        (
          gsutil cp gs://${_CACHE_BUCKET}/mvn/m2-function-cache.tar.gz /tmp/m2-function-cache.tar.gz && \
          tar -xzf /tmp/m2-function-cache.tar.gz
        ) || echo 'Cache not found'
    volumes:
      - name: m2
        path: /root/.m2/

  - name: gcr.io/cloud-builders/mvn
    id: build
    args:
      - package
    volumes:
      - name: m2
        path: /root/.m2/

  - name: gcr.io/cloud-builders/gsutil
    waitFor:
      - build
    dir: /root
    entrypoint: bash
    args:
      - -c #TODO check command not found when execute tar -czf
      - |
        tar -czf /tmp/m2-function-cache.tar.gz /root/.m2 && \ 
        gsutil cp /tmp/m2-function-cache.tar.gz gs://${_CACHE_BUCKET}/mvn/m2-function-cache.tar.gz
    volumes:
      - name: m2
        path: /root/.m2/

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Store on gcs
    dir: target/deployment
    args:
      - 'cp'
      - 'test-quarkus-1.0-SNAPSHOT-runner.jar'
      - 'gs://$_CACHE_BUCKET/functions/discover/test-quarkus-1.0-SNAPSHOT-runner.jar'

  - name: 'gcr.io/$PROJECT_ID/gcloud'
    id: Deploy functions
    args:
      - -c
      - |
        gcloud functions deploy quarkus-example-funky-pubsub \
        --gen2 \
        --memory="256Mi"  \
        --max-instances=2 \
        --region=$_REGION \
        --vpc-connector=$_VPC_CONNECTOR \
        --entry-point=io.quarkus.funqy.gcp.functions.FunqyBackgroundFunction \
        --runtime=java11 \
        --trigger-resource $_TOPIC \
        --trigger-event google.pubsub.topic.publish \
        --source=target/deployment
